import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import initializeApollo from "../lib/apollo";
import gql from "graphql-tag";
import { useMutation, useQuery } from "@apollo/client";
import { USERS_QUERY } from "../graphql/queries";
import { CREATE_USER } from "../graphql/mutations";

const Home = () => {
  const [email, setEmail] = useState("");
  const [username, setUsername] = useState("");
  const { data, error, loading } = useQuery(USERS_QUERY);

  const [createUser] = useMutation(CREATE_USER);

  const handleAdd = () => {
    createUser({
      variables: {
        email: email,
        username: username,
      },
      // refetchQueries: [
      //   {
      //     query: gql`
      //       query fetchUsers {
      //         users {
      //           id
      //           username
      //           email
      //         }
      //       }
      //     `,
      //   },
      // ],
      update: (store, { data: { insert_users_one } }) => {
        const data = store.readQuery({
          query: USERS_QUERY,
        });

        store.writeQuery({
          query: USERS_QUERY,
          data: {
            users: [...data.users, insert_users_one],
          },
        });
      },
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading && <div>loading...</div>}
      {data &&
        data.users.map((user) => <p key={`${user.id}`}>{user.username}</p>)}
      <input
        type="text"
        value={email}
        onChange={({ target }) => setEmail(target.value)}
      ></input>
      <input
        type="text"
        value={username}
        onChange={({ target }) => setUsername(target.value)}
      ></input>
      <button onClick={() => handleAdd()}> add user</button>
    </div>
  );
};

export async function getStaticProps(context) {
  // const options = {
  //   method: "POST",
  //   headers: {
  //     "Content-Type": "application/json",
  //     "x-hasura-admin-secret":
  //       "LgMSSBSV0SS0qTW7ZjVMI4w4023Oz93j0HCFfXb6CqYSckGkBS4vQEYmwknFd3e4",
  //   },
  //   body: JSON.stringify({
  //     query: `query fetchUsers {
  //       users {
  //         id
  //         username
  //         email
  //       }
  //     }
  //     `,
  //     opertaionName: "fetchUsers",
  //   }),
  // };
  // const response = await fetch(
  //   "https://liked-aardvark-96.hasura.app/v1/graphql",
  //   options
  // );
  const client = initializeApollo();
  const { data } = await client.query({
    query: gql`
      query fetchUsers {
        users {
          id
          username
          email
        }
      }
    `,
  });
  // const data = await response.json();
  console.log(`data`, data);
  // console.log(`data`, data.data.users);
  return {
    props: {}, // will be passed to the page component as props
  };
}

export default Home;
